baseURL = "https://dmitriy5181.github.io"
title = "// pragmatic engineering"
theme = "contrast-hugo"

# see https://gohugo.io/getting-started/configuration/#configure-front-matter
[frontmatter]
    date  = [":filename", ":default"]
